version: 1.1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: dotnet restore ./src
- ps: >-
    sc .\src\CTRC\CTRC.csproj $(gc .\src\CTRC\CTRC.csproj).replace('<Version>1.0.0</Version>','<Version>' + $env:appveyor_build_version + '</Version>')
build:
  verbosity: minimal
deploy: off