version: 9.0.0.{build}
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- cmd: dotnet restore .
build:
  publish_nuget: true
  verbosity: minimal
deploy: off